FROM python:3.7.3-stretch

ADD requirements.txt /tmp/

RUN apt-get update && \
    apt-get install -y  wkhtmltopdf \
    ffmpeg \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash \
    git-lfs 

RUN pip install --upgrade -r /tmp/requirements.txt

CMD echo "running ...." >> /logs && tail -f  /logs